### PR TITLE
Windows Musawo Logo 

### PR DESCRIPTION
**Pull request by Victorayo**
There is an attached file I uploaded on the main branch. 
Try and open it to check for the logo and Icons.

I'm sorry it took a while before I respond. I was busy with other projects.

Pls after checking, kindly drop your feedback

light

### CODE REVIEW

**Review by RonnieLutalo — COMMENTED** [review]
Is it possible to have this cover Image design without these circled elements on it? Is there some idea behind having it there? If so, kindly share the idea behind. It would be great if this cover image design can be without those circled elements. Ideally, you could remove them and then balance visual weight by dragging the text on the left vertically down slightly to balance. Thank you so much once again for these contributions.
desigssssssssss

**Comment by Victorayo** [comment]
> Is it possible to have this cover Image design without these circled elements on it? Is there some idea behind having it there? If so, kindly share the idea behind. It would be great if this cover image design can be without those circled elements. Ideally, you could remove them and then balance visual weight by dragging the text on the left vertically down slightly to balance. Thank you so much once again for these contributions.
> desigssssssssss
> 

Hi Ronnie, actually there's no reason for the signature. I will remove and adjust just as you've asked.

**Comment by Victorayo** [comment]
> These look great. Also Just realized at some point we might find it challenging when we keep adding the designs in the root folder. Can you please create a new folder named named "**assets**" and then place all the designed assets into that folder for organization and easier access in the future? Thank you for your contributions. 

I wasn't able to create any file/folder on the branch. I think the security you added restrict me. Only if you create it from your end. Then I can be able to add those designs there.

**Comment by RonnieLutalo** [comment]
> > These look great. Also Just realized at some point we might find it challenging when we keep adding the designs in the root folder. Can you please create a new folder named named "**assets**" and then place all the designed assets into that folder for organization and easier access in the future? Thank you for your contributions.
> 
> I wasn't able to create any file/folder on the branch. I think the security you added restrict me. Only if you create it from your end. Then I can be able to add those designs there.

Thanks for that feedback. As a quick fix before I I trouble shoot this (why a contributor can't create a folder). I have created an **assets** folder so you may move them there.  Just pull down those changes and try working with that.

**Comment by Victorayo** [comment]
> > > These look great. Also Just realized at some point we might find it challenging when we keep adding the designs in the root folder. Can you please create a new folder named named "**assets**" and then place all the designed assets into that folder for organization and easier access in the future? Thank you for your contributions.
> > 
> > I wasn't able to create any file/folder on the branch. I think the security you added restrict me. Only if you create it from your end. Then I can be able to add those designs there.
> 
> Thanks for that feedback. As a quick fix before I I trouble shoot this (why a contributor can't create a folder). I have created an **assets** folder so you may move them there.  Just pull down those changes from the main branch and try working with that.

Noted boss

**Comment by Victorayo** [comment]
> Is it possible to have this cover Image design without these circled elements on it? Is there some idea behind having it there? If so, kindly share the idea behind. It would be great if this cover image design can be without those circled elements. Ideally, you could remove them and then balance visual weight by dragging the text on the left vertically down slightly to balance. Thank you so much once again for these contributions.
> desigssssssssss
> 


Here is the change.

**Comment by Victorayo** [comment]
> Is it possible to have this cover Image design without these circled elements on it? Is there some idea behind having it there? If so, kindly share the idea behind. It would be great if this cover image design can be without those circled elements. Ideally, you could remove them and then balance visual weight by dragging the text on the left vertically down slightly to balance. Thank you so much once again for these contributions.
> desigssssssssss
> 

Here are two copies I made after removing the signature.

**Review by RonnieLutalo — APPROVED** [review]

**Comment by RonnieLutalo** [comment]
Thank you so much @Victorayo. These LGTM 🚀

**Pull request merged**
